Repository 4DModeller/fdmr, pull requests merged in 2023-09, with the labels that each got.

#121 Fix read of sd from model output
  CHANGELOG.md
  R/model_parse.R
  vignettes/priors.Rmd
Labels: bug

#130 Move from using `archive` to `untar`
  CHANGELOG.md
  DESCRIPTION
  R/util_retrieve.R
  tests/testthat/setup.R
Labels: enhancement

#140 Add a table to summarize the expected data format
  vignettes/data_preprocessing.Rmd
Labels: documentation

#126 Update main page description
  README.md
  vignettes/DecisionTree.Rmd
  vignettes/inlaFAQ.Rmd
Labels: documentation, high-priority

#141 A tutorial using simulated Gaussian data
  vignettes/Simulation_GaussianDat.Rmd
Labels: documentation, high-priority

#128 End to end tutorial using simulated Poisson data
  vignettes/Simulation_PoissonDat.Rmd
Labels: documentation, high-priority
