Repository 4DModeller/fdmr, pull requests merged in 2023-11, with the labels that each got.

#235 Release 0.1.1
  .github/workflows/check-standard.yaml
  CHANGELOG.md
  DESCRIPTION
  R/model_parse.R
  R/plot_mapping.R
  R/plot_mesh.R
  R/plot_priors.R
  R/shiny_meshbuilder.R
  R/shiny_modelbuilder.R
  R/shiny_modelviewer.R
  R/shiny_priors.R
  R/util_coords.R
  R/util_paths.R
  R/util_shiny.R
  README.md
  _pkgdown.yml
  man/model_builder.Rd
  man/model_builder_shiny.Rd
  vignettes/covid.Rmd
  vignettes/covid_mcmc.Rmd
  vignettes/decision_tree.Rmd
  vignettes/expected_data_structure.Rmd
  vignettes/getting_started.Rmd
  vignettes/hydro.Rmd
  vignettes/inla_FAQ.Rmd
  vignettes/modelbuilder.Rmd
  vignettes/priors.Rmd
  vignettes/simulation_gaussian_data.Rmd
  vignettes/simulation_poisson_data.Rmd
Labels: release

#261 Update README.md to have contributor guidelines
  README.md
Labels: release-2

#264 Bringing slightly edited geophysical tutorial into vignettes
  CHANGELOG.md
  vignettes/data/MT_Svalbard_Z.csv
  vignettes/tutorial_geophysics.Rmd
Labels: documentation

#259 Snow
  vignettes/data/Bayelva_snow.nc
  vignettes/data/Bayelva_snow_geo.nc
  vignettes/snow.Rmd
  vignettes/snow.html
Labels: documentation, hackathon-23

#280 added full formula creator
  R/fit_model.R
Labels: utrecht-sprint

#284 Iss273/new data sets
  vignettes/fitmodel_data/datasets.md
  vignettes/fitmodel_data/make_final_data.py
  vignettes/fitmodel_data/rain_data.csv
  vignettes/fitmodel_rain.Rmd
Labels: utrecht-sprint
