Repository 4DModeller/fdmr, pull requests merged in 2023-10, with the labels that each got.

#156 Update the parameter labels and help descriptions for Shiny app
  R/shiny_priors.R
Labels: high-priority, shiny

#147 1. Adds map plot of model output to priors app
  CHANGELOG.md
  DESCRIPTION
  NAMESPACE
  R/model_parse.R
  R/shiny_priors.R
  _pkgdown.yml
  man/model_builder.Rd
  man/model_builder_shiny.Rd
  vignettes/Simulation_GaussianDat.Rmd
  vignettes/Simulation_PoissonDat.Rmd
  vignettes/priors.Rmd
  vignettes/priors_app.Rmd
Labels: enhancement

#180 Iss176/fix intercept
  CHANGELOG.md
  R/shiny_priors.R
  vignettes/covid.Rmd
  vignettes/covid_mcmc.Rmd
  vignettes/hydro.Rmd
  vignettes/priors.Rmd
  vignettes/simulation_gaussian_data.Rmd
  vignettes/simulation_poisson_data.Rmd
Labels: enhancement

#183 Added disabling of exposure dropdown when using Gaussian data
  CHANGELOG.md
  DESCRIPTION
  R/shiny_priors.R
Labels: enhancement

#197 A documentation about the expected data structure
  R/util_paths.R
  _pkgdown.yml
  vignettes/expected_data_structure.Rmd
Labels: documentation

#214 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: hackathon-23
